#!/bin/bash

source ${HOME}/.logging

dry_run=false

while getopts ":d" opt; do
  case ${opt} in
    d) dry_run=true ;;
  esac
done

setup_scripts=$(ls ${HOME}/.yadm/setup/*.sh | sort -n -t _ -k 2)
log_info "Found ${#setup_scripts[*]} setup scripts"
for file in ${setup_scripts}
do
  log_info "=> Executing ${file}"
  test -h ${file} && log_info "==> Target: $(readlink ${file})"
  if [ "${dry_run}" = false ]; then
    /bin/bash ${file}
  fi
  log_info "==> Finishing executing ${file}: Exit ${?}"
done
