#!/bin/bash

source ${HOME}/.logging

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

dry_run=false

while getopts ":d" opt; do
  case ${opt} in
    d) dry_run=true ;;
  esac
done

setup_scripts=$(ls ${DIR}/setup/*.sh | sort -n -t _ -k 2)
log_info "Found ${#setup_scripts[*]} setup scripts"
for file in ${setup_scripts}
do
  if test -h "${file}"; then
    original_file="(target: $(readlink ${file}))"
  fi
  
  log_info "=> Executing ${file} ${original_file}"
  if [ "${dry_run}" = false ]; then
    /bin/bash ${file}
  fi
  log_info "==> Finished executing ${file}: Exit ${?}"
done

