#!/usr/bin/env sh

__git_clean_branches_complete() {
  branches=$(git branch --all --format='%(refname:short)')
  COMPREPLY=($(compgen -W "$branches" -- "$2"))
}

complete -F __git_clean_branches_complete git-clean-branches

