#!/usr/bin/env sh

set -e

DEFAULT_NAMESPACE="kube-system"
SCRIPT_NAME=${0##*/}

function banner () {
  echo "========================================================================="
}

function usage () {
cat << USAGE  
  Usage: ${SCRIPT_NAME} -s <secret> -n <namespace>
     -s --secret      The secret to retrieve. Partial secret names will return all matching tokens.
                      Can be repeated multiple times.
     -l --list        List all possible secrets and tokens
     -n --namespace   The namespace to search. Defaults to ${DEFAULT_NAMESPACE}
     -k --kubeconfig  The kube config to use. Defaults to the environment variable 'KUBECONFIG'
     -q --quiet       Suppress output
USAGE
}

secrets=()
list=0
quiet=0
kube_config=${KUBECONFIG}
namespace=${DEFAULT_NAMESPACE}

SHORTOPTS="s:n:k:lhq"
LONGOPTS="secret:,namespace:,kubeconfig:,list,help,quiet"
REQUIREDOPTS=("kube_config")
if ! options=$(getopt -n "${SCRIPT_NAME}" -o "${SHORTOPTS}" -l "${LONGOPTS}" -- "$@"); then
  log_error "Unable to set cli options"
  exit 1
fi

eval set -- "${options}"
while [ $# -gt 0 ]; do
  case "$1" in
    -s|--secret) shift; secrets+=("${1}") ;;
    -n|--namespace) shift; namespace="${1}" ;;
    -k|--kubeconfig) shift; kube_config="${1}" ;;
    -l|--list) list=1 ;;
    -q|--quiet) quiet=1 ;;
    -h|--help) usage; exit 0 ;;
    --) shift; break ;;
    *) break ;;
  esac
  shift
done

if [[ ${quiet} -eq 0 ]]; then
  log_info "Using the following option(s):"
  for o in "list" "quiet" "secrets" "kube_config" "namespace"; do
    log_info "- ${o}: ${!o}"
  done
fi

for required in ${REQUIREDOPTS}; do
  if [[ -z "${!required}" ]]; then
    log_error "Required parameter missing [${required}]"
    usage
    exit 1
  fi
done

if [[ ${list} -eq 0 ]] && [[ ${#secrets[@]} -eq 0 ]]; then
  log_error "Must specify either list all or a secret to search for"
  usage
  exit 1
fi

if [[ ${quiet} -eq 0 ]]; then
  log_info "Attempting to retrieve the following from kubernetes using kubectl config [${KUBECONFIG}] from namespace [${namespace}]..."
fi

json=$(KUBECONFIG=${kube_config} kubectl get secrets -n ${namespace} -o json)
results=()
if [[ ${list} -eq 1 ]]; then
  results+=("$(echo "${json}" | jq -r '.items[] | select(.metadata.name) | [.metadata.name, .data.token] | @tsv')")
else
  for secret in "${secrets[@]}";
  do
    results+=("$(echo "${json}" | jq -r --arg VAL "${secret}" '.items[] | select(.metadata.name | contains($VAL)) | [.metadata.name, .data.token] | @tsv')")
  done
fi

for r in "${results[@]}"; do
  echo "${r}" | while IFS=$'\t' read -r name token; do
    if [[ ! -z "${token}" ]]; then
      if [[ ${list} -eq 1 ]] || [[ ${quiet} -eq 0 ]]; then
        log_info
        log_info "${name}"
        banner
        echo "$(echo ${token} | base64 --decode)"
        banner
      else
        echo "$(echo ${token} | base64 --decode)"
      fi
    fi
  done
done

if [[ ${quiet} -eq 0 ]]; then
  log_info "Done!"
fi

exit 0
