#!/usr/bin/env sh

function _export_kubeconfig () {
  local kube_conf="${1}"
  local conf_dir="${KUBECONFIG_HOME:-${HOME}/.kube/conf}"
  if [[ ! -d ${conf_dir} ]]; then
    log_error "Kube config directory does not exist @ [${conf_dir}]"
    return 1
  fi

  if [[ ! -z "${kube_conf}" ]]; then
    konfig_file="${conf_dir}/${kube_conf}.kubeconfig"   
  else
    PS3="Select a kube config (${conf_dir}): "
    files=($(ls -1 ${conf_dir}/*.kubeconfig | xargs -I{} -n 1 basename {} .kubeconfig))

    select opt in "${files[@]}" "Quit";
    do
      if [ "${opt}" = "Quit" ]; then
        return 0
      fi
      konfig_file="${conf_dir}/${opt}.kubeconfig"
      break
    done
    
  fi
  
  if [ ! -e "${konfig_file}" ]; then
    log_error "Kube config for ${opt} not found (${konfig_file})"
    return 1
  fi

  log_info "Setting Kubectl config to '${konfig_file}'"
  export KUBECONFIG=${konfig_file}
  log_info " > KUBECONFIG      ${KUBECONFIG}"
  return 0
}

alias export-kubeconfig="_export_kubeconfig"
