#!/usr/bin/env sh

_source ${HOME}/.logging

function _export_kubeconfig () {
  local conf_dir="${KUBECONFIG_HOME:-${HOME}/.kube/conf}"
  if [[ ! -d ${conf_dir} ]]; then
    log_error "Kube config directory does not exist @ [${conf_dir}]"
    return 1
  fi

  PS3="Select a kube config (${conf_dir}): "
  files=($(ls -1 ${conf_dir}/kubeconfig-* | xargs -n 1 basename))

  select opt in "${files[@]}" "Quit";
  do
    if [ "${opt}" = "Quit" ]; then
      return 0
    fi
    konfig_file="${conf_dir}/${opt}"
    if [ ! -e "${konfig_file}" ]; then
      log_error "Kube config for ${opt} not found (${konfig_file})"
      return 1
    fi
    log_info "Setting Kubectl config to '${konfig_file}'"
    export KUBECONFIG=${konfig_file}
    log_info " > KUBECONFIG      ${KUBECONFIG}"
    log_info " > Dashboard Token $(get-kubernetes-secret --secret dashboard-kubernetes-dashboard-token --quiet)"
    return 0
  done
}

alias export-kubeconfig="_export_kubeconfig"
