#!/usr/bin/env sh

_export_kubeconfig () {
  kube_conf="${1}"
  conf_dir="${KUBECONFIG_HOME:-${HOME}/.kube/conf}"
  if [[ ! -d ${conf_dir} ]]; then
    echoerr "Kube config directory does not exist @ [${conf_dir}]"
    return 1
  fi

  if [[ ! -z "${kube_conf}" ]]; then
    konfig_file="${conf_dir}/${kube_conf}.kubeconfig"
  else
    PS3="Select a kube config (${conf_dir}): "
    files=($(ls -1 ${conf_dir}/*.kubeconfig | xargs -I{} -n 1 basename {} .kubeconfig))

    COLUMNS=10
    select opt in "${files[@]}" "Quit";
    do
      if [ "${opt}" = "Quit" ]; then
        unset COLUMNS
        return 0
      fi
      konfig_file="${conf_dir}/${opt}.kubeconfig"
      break
    done
    unset COLUMNS
  fi

  if [ ! -e "${konfig_file}" ]; then
    echoerr "Kube config for ${opt} not found (${konfig_file})"
    return 1
  fi

  if [ "${KUBECONFIG}" != "${konfig_file}" ]; then
    export KUBECONFIG=${konfig_file}
    echo "> KUBECONFIG ${KUBECONFIG}"
  fi

  return 0
}

alias export-kubeconfig="_export_kubeconfig"
