#!/usr/bin/env sh

function _get_location () {
  location=$(curl -s http://ip-api.com/json)

  echo "IP:  $(echo ${location} | jq -r .query)"
  echo "LOC: $(echo ${location} | jq -r '.city + " " + .zip + ", " + .regionName')"
}

alias what-is-my-location="_get_location"
