#!/usr/bin/env sh

FILE="${HOME}/.aws_accounts"

_export_aws_creds () {
  if [ ! -e ${FILE} ]; then
    echoerr "AWS accounts file '${FILE}' not found"
    return 1
  fi

  accounts=()
  while IFS='\n' read -r account || [[ -n "${account}" ]]; do
    [[ "${account}" =~ ^#.*$ ]] && continue
    accounts+=("${account}")
  done < "${FILE}"
  accounts=($(printf '%s\n' "${accounts[@]}" | sort))

  if [[ "${1}" == "-l" ]] || [[ "${1}" == "--list" ]]; then
    echo "Accounts:"
    for account in "${accounts[@]}"; do
      name=$(echo ${account} | cut -f1 -d:)
      id="$(echo ${account} | cut -f2 -d:)"
      echo "- ${name}: ${id}"
    done
    return 0
  fi

  if [ ! -z ${1} ]; then
    export AWS_PROFILE="${1}"
    export AWS_DEFAULT_PROFILE="${1}"
    echo "> AWS_PROFILE ${AWS_PROFILE}"
    echo "> AWS_DEFAULT_PROFILE ${AWS_DEFAULT_PROFILE}"
    return 0
  fi

  PS3="Select account: "
  
  trap "{ unset COLUMNS; return 0; }" SIGINT SIGTERM SIGEXIT
  COLUMNS=10
  select account in "${accounts[@]}" "Exit";
  do
      case "${account}" in
        "Exit")
          return 0
          ;;
        *)
          name=$(echo ${account} | cut -f1 -d:)
          id="$(echo ${account} | cut -f2 -d:)"
          export AWS_PROFILE="${id}"
          export AWS_DEFAULT_PROFILE="${id}"
          echo "> ${name}"
          echo "> AWS_PROFILE ${AWS_PROFILE}"
          echo "> AWS_DEFAULT_PROFILE ${AWS_DEFAULT_PROFILE}"
          return 0
          ;;
      esac
  done
}

alias export-aws-creds="_export_aws_creds"
