#!/usr/bin/env sh

DEFAULT_KUBECONFIG_HOME="${HOME}/.kube/conf"

_export_kubeconfig () {
  kube_conf="${1}"
  conf_dir="${KUBECONFIG_HOME:-${DEFAULT_KUBECONFIG_HOME}}"
  if [[ ! -d ${conf_dir} ]]; then
    echoerr "Kube config directory does not exist @ [${conf_dir}]"
    return 1
  fi

  if [[ ! -z "${kube_conf}" ]]; then
    konfig_file="${conf_dir}/${kube_conf}.kubeconfig"
  else
    trap "{ unset COLUMNS; return 0; }" SIGINT SIGTERM SIGEXIT

    PS3="Select a kube config (${conf_dir}): "
    echo "ls -1 ${conf_dir}/*.kubeconfig | xargs -I{} -n 1 basename {} .kubeconfig"
    files=($(ls -1 ${conf_dir}/*.kubeconfig | xargs -I{} -n 1 basename {} .kubeconfig))

    COLUMNS=10
    select opt in "${files[@]}" "Exit";
    do
      case "${opt}" in
        "Exit")
          return 0
          ;;
        *)
          konfig_file="${conf_dir}/${opt}.kubeconfig"
          break
          ;;
      esac
    done
  fi

  if [ ! -e "${konfig_file}" ]; then
    echoerr "Kube config for ${opt} not found (${konfig_file})"
    return 1
  fi

  if [ "${KUBECONFIG}" != "${konfig_file}" ]; then
    export KUBECONFIG=${konfig_file}
    echo "> KUBECONFIG ${KUBECONFIG}"
  fi

  return 0
}

alias export-kubeconfig="_export_kubeconfig"
