#!/usr/bin/env sh

_kubeconfig_exists () {
  kube_conf="${1}"
  conf_dir="${KUBECONFIG_HOME:-${HOME}/.kube/conf}"
  konfig_file="${conf_dir}/${kube_conf}.kubeconfig"

  if [ ! -e "${konfig_file}" ]; then
    return 1
  fi
  return 0
}

alias kubeconfig-exists="_kubeconfig_exists"
