#!/usr/bin/env sh

_tf_plan_file() {
  workspace=$(cat .terraform/environment 2>/dev/null || echo 'default')
  mktemp -t "tf-plan_${workspace}"
}

_tf_workspace() {
  workspace="${1}"
  if [ -z "${workspace}" ]; then
    terraform workspace show
  else
    terraform workspace select "${workspace}"
  fi
}

_tf_variables_file() {
  variables_file="${PWD%%/}/$(_tf_workspace).tfvars"

  if [ -r ${variables_file} ]; then
    relative_path=$(realpath --relative-to="$(pwd)" "${variables_file}")
    echo "-var-file=${relative_path}"
  else
    echo ""
  fi
}

# aliases
alias tf-init="terraform init"
alias tf-plan="terraform plan -detailed-exitcode $(_tf_variables_file) -out=$(eval _tf_plan_file)"
alias tf-apply="terraform apply $(_tf_variables_file)"
alias tf-refresh="terraform refresh $(_tf_variables_file)"
alias tf-fmt="terraform fmt"
alias tf-workspace="_tf_workspace"
alias tf-ls-workspace="terraform workspace list"

