#!/usr/bin/env sh

PS3="Select a kube config: "
files=($(ls -1 ${HOME}/.kube/*.kubeconfig | xargs -n 1 basename))
select konfig in "${files[@]}" "Quit";
do
  if [ "${konfig}" = "Quit" ]; then
    exit 0
  fi
  konfig_file="${HOME}/.kube/${konfig}"
  if [ ! -e "${konfig_file}" ]; then
    echo "Kube config for ${konfig} not found (${konfig_file})"
    exit 1
  fi
  echo "Setting Kubectl config to '${konfig}'"
  export KUBECONFIG=${konfig_file}
  echo " > KUBECONFIG ${KUBECONFIG}"
  exit 0
done

