#!/usr/bin/env sh

DEFAULT_NAMESPACE="kube-system"

function usage () {
  script=$(basename "${0}")
  echo "Usage: ${script} -s <secret> -n <namespace>"
  echo "   -s the secret to retrieve"
  echo "   -n the namespace to search. Defaults to ${DEFAULT_NAMESPACE}"
}

secret=""
namespace=${DEFAULT_NAMESPACE}
while getopts ":hs:n:" o; do
  case "${o}" in
    s)
      secret="${OPTARG}"
      ;;
    n)
      namespace="${OPTARG}"
      ;;
    h)
      usage
      exit 0
      ;;
    :) 
      printf "missing argument for -%s\n" "$OPTARG" >&2
      echo "$usage" >&2
      exit 1
      ;;  
    *)
      usage
      exit 0
      ;;
  esac
done
shift $((OPTIND - 1))

if [[ -z "${secret}" ]]; then
  echo "No secret name provided!"
  usage
  exit 1
fi

echo "Getting secret [${secret}] from namespace [${namespace}]"

result=$(kubectl get secrets -n ${namespace} -o json | jq -r --arg VAL "${secret}" '.items[] | select(.metadata.name | contains($VAL)) | .data.token')
if [ "${?}" != "0" ]; then
  exit 1
fi
decoded=$(echo ${result} | base64 --decode)
echo "Result >>>"
echo "\"${decoded}\""
