#!/usr/bin/env sh

DEFAULT_NAMESPACE="kube-system"

function banner () {
  echo "=========================================="
}

function usage () {
  script=$(basename "${0}")
  echo "Usage: ${script} -s <secret> -n <namespace>"
  echo "   -s the secret to retrieve. Partial secret names will return all matching tokens"
  echo "   -n the namespace to search. Defaults to ${DEFAULT_NAMESPACE}"
  echo "   KUBECONFIG must be set before running!"
}

secret=""
namespace=${DEFAULT_NAMESPACE}
while getopts ":hs:n:" o; do
  case "${o}" in
    s)  secret="${OPTARG}"
        ;;
    n)  namespace="${OPTARG}"
        ;;
    h)  usage
        exit 0
        ;;
    :)  echo "Missing argument for -${OPTARG}"
        usage
        exit 1
        ;;  
    *)  echo "Unrecognised argument for -${OPTARG}"
        usage
        exit 1
        ;;
  esac
done
shift $((OPTIND - 1))

if [[ -z "${secret}" || -z "${namespace}" || -z "${KUBECONFIG}" ]]; then
  echo "Missing required parameters:"
  echo "> -s         secret         [${secret}]"
  echo "> -n         namespace      [${namespace}]"
  echo "> KUBECONFIG kubectl config [${KUBECONFIG}]"
  usage
  exit 1
fi

echo "Attempting to retrieve the following from kubernetes using kubectl config [${KUBECONFIG}]:"
echo "> secret    ${secret}"
echo "> namespace ${namespace}"

json=$(kubectl get secrets -n ${namespace} -o json)
result=$(echo "${json}" | jq -r --arg VAL "${secret}" '.items[] | select(.metadata.name | contains($VAL)) | [.metadata.name, .data.token] | @tsv')
echo "${result}" | while IFS=$'\t' read -r name token; do
  if [[ ! -z "${token}" ]]; then
    echo
    echo
    echo "${name}"
    banner
    echo "\"$(echo ${token} | base64 --decode)\""
    banner
  fi
done

