#!/usr/bin/env sh

setup_scripts=$(ls ${cwd}/setup/*.sh | sort -n -t _ -k 2)
echo "Found ${#setup_scripts[*]} setup scripts"
for file in ${setup_scripts}
do
  echo "> Executing ${file} ..."
  . ${file}
  echo "> Finishing executing ${file}: Exit ${?}"
done
